apiVersion: v1
kind: Service
metadata:
  name: playlists
  labels:
    app: server
spec:
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlists
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: amokkp/devops-final-server:latest
          ports:
            - containerPort: 3002